boostcampwm-2024/web36-QLab

- be/package-lock.json
- be/package.json
- be/src/app.module.ts
- be/src/query/query.module.ts
- be/src/query/query.service.spec.ts
- be/src/query/query.service.ts
- be/src/shell/shell.controller.spec.ts
- be/src/shell/shell.controller.ts
- be/src/shell/shell.module.ts
- be/src/shell/shell.service.spec.ts
- be/src/shell/shell.service.ts
- be/src/user/user.controller.spec.ts
- be/src/user/user.controller.ts
- be/src/user/user.module.ts
- be/src/user/user.service.spec.ts
- be/src/user/user.service.ts
- `@nest/typeOrm` , `typeOrm` 추가
- 쿼리 모듈
- 유저 모듈
- 쉘 모듈
> 네스트 기본 모듈 구조 세팅

- be/Jenkinsfile
빌드/배포 자동화를 위한 `Jenkinsfile` 추가
https://spiffy-centipede-875.notion.site/Jenkins-CICD-0a88a142c3c34512bcef75ff284fd3c4?pvs=4
> jenkins 파일 추가

- FE/Dockerfile
- be/Dockerfile
- docker-compose.yml
- nginx/Dockerfile
- nginx/nginx.conf
FE, BE, 웹 세개의 서버를 도커로 감싸고, 하나의 인스턴스 안에서 실행합니다.
```
docker-compose up --build
```
로컬에서 실행 후 80 포트로 접속하여 프론트 페이지 배포를 확인 할 수 있습니다.
로컬에서 실행 시 프론트 웹 서버만 정상적으로 배포되는 걸 확인할 수 있습니다.
로컬 테스트 환경 `docker-compose.test.yml` 은 추가적으로 구성할 예정입니다.
> [#74] 도커 파일, 컴포즈 파일 작성

- FE/package-lock.json
- FE/src/api/__mocks__/axiosMock.ts
- FE/src/api/shellApi.ts
- FE/src/components/Shell.tsx
- FE/src/components/ShellList.tsx
- FE/src/constants.ts
- FE/src/hooks/useCustomMutation.ts
- FE/src/hooks/useShellQuery.tsx
- FE/src/pages/MainPage.tsx
- FE/src/types/interfaces.ts
쉘 fetch, add, update, remove 로직 및 api 요청 로직을 추가하였습니다. 
- useCustomMutate 훅을 만들어서 낙관적 업데이트 및 에러처리를 다양한 API 호출에 범용적으로 쓸 수 있게 하였습니다. 
- 쉘 fetch, add, update, remove 로직 및 api 요청 로직을 추가하였습니다.
- 쉴 컴포넌트의 키값을 생성시간에서 uuid로 변경
- 쉘 컴포넌트의 shelld값을 서버에서 받아올 수 있게 로직 수정
> [#11 #37 #38 #14] shell 조작 api 로직 추가

- BE/src/config/query-database/single-mysql.adapter.ts
- BE/src/interceptors/serialize.interceptor.ts
- BE/src/query/dto/res-query.dto.ts
- BE/src/query/query.controller.ts
- BE/src/shell/dto/res-shell-result.dto.ts
- BE/src/shell/dto/res-shell.dto.ts
- BE/src/shell/shell.controller.ts
> shell DTO를 추가

- FE/Dockerfile
- Jenkinsfile
`dev` 브랜치에 PR 요청 시, CI Test 를 자동화 합니다.
> [#45] dev 브랜치에 merge 시 테스트 자동화를 구축한다. 

- FE/src/api/__mocks__/axiosMock.ts
- FE/src/components/Shell.tsx
- FE/src/components/ShellList.tsx
- FE/src/hooks/useCustomMutation.ts
- FE/src/util.ts
쉘 또는 x버튼을 여러번 눌러야 작동하는 이슈를 해결했습니다.
<br>
- 중복 키로 인해 발생한 에러 수정
- 쉘을 두번 클릭해야 focus 되는 버그 수정
- x버튼을 두번 눌러야 쉘이 지워지는 버그 수정
<br>
<br>
<br>
> [#114] input 두번 눌러야 포커스 되는 이슈 해결

- FE/src/util.ts
close #102 
close #105 
gui를 통해 사용자가 테이블 생성 및 수정을 할때 이를 sql로 변환 시켜줍니다.
utils에 sql 변환 함수 로직 작성
> [#102,#105] 테이블 생성,수정에 대해서 SQL로 변환한다.

- FE/src/api/__mocks__/mockTables.ts
- FE/src/api/tableApi.ts
- FE/src/components/Shell.tsx
- FE/src/components/ViewTable.tsx
- FE/src/constants.ts
- FE/src/hooks/useShellQuery.tsx
- FE/src/hooks/useTableQuery.ts
쉘 실행시 특정 쿼리에 한정해 refetch 요청을 보내 테이블 정보를 업데이트합니다.
<br>
<br>
> [#120] 테이블이 변경되는 쿼리 실행시 해당 테이블의 정보를 가져온다.

- Jenkinsfile
> 젠킨스파일 오타 수정

- Jenkinsfile
> QLab 1.1.0 배포

- FE/package-lock.json
- FE/package.json
- FE/src/components/LeftSidebar.tsx
- FE/src/components/TableTool.tsx
- FE/src/components/ui/checkbox.tsx
- FE/src/components/ui/dialog.tsx
- FE/src/components/ui/select.tsx
- FE/src/constants.ts
- FE/src/pages/MainPage.tsx
- FE/src/types/interfaces.ts
- FE/src/util.ts
테이블 추가/수정 레이아웃을 만들었습니다. 
<br>
테이블 선택 버튼, 테이블 레이아웃, 드롭 메뉴, 체크박스, 테이블 추가 버튼 & 팝업, 쿼리 생성 버튼
<br>
<br>
> [#104] 테이블 추가 레이아웃을 만든다.

- nginx/nginx.conf
q-lab.site 로 접속 시 `CORS` 문제를 해결하기 위해 www.q-lab.site 로 리디렉션 되도록 해주었습니다.
> feat : q-lab.site 접속 시 www.q-lab.site 로 리디렉션 되도록 처리

- FE/src/api/shellApi.ts
- FE/src/components/EditableInput.tsx
- FE/src/components/Shell.tsx
- FE/src/components/ShellList.tsx
- FE/src/components/TableTool.tsx
- FE/src/components/ViewTable.tsx
- FE/src/hooks/useShellHandler.ts
- FE/src/hooks/useShellQuery.tsx
- FE/src/util.ts
- 쉘 수정, 생성 등 테이블 GUI 조작에 따라 쿼리문 생성
- 쉘을 추가한 뒤 생성된 쿼리를 넣어줍니다.
<br>
- 테이블 GUI 입력 로직 
- 기존 테이블 형식을 쿼리 생성용 테이블 형식으로 변환하는 유틸함수 추가
- 쿼리 생성 버튼 클릭시 쉘을 추가하고 생성된 쿼리문을 넣어주는 로직 구현
- shell 핸들러 함수를 커스텀 훅으로 분리
<br>
<br>
> [#103] 새로운 쉘을 생성하고, 해당 쉘에 쿼리문을 넣어준다.

- docker-compose.yml
- nginx/Dockerfile
- nginx/nginx.conf
#164 
http -> https
근데 제대로 동작하는지는 머지된 이후에 확인할 수 있을 듯 합니다,,,,,,
저희 서버에 `letsencrypt`로 인증키를 발급받아두었습니다.
nginx 설정 파일, dockerfile, docker-compose 파일을 수정하였습니다.
- 443 포트 허용
- 인증키 복사
- url 리다이렉트
설정 과정에 대한 자세한 설명들은 개발일지에 작성해두었습니다.
[HTTPS](https://www.notion.so/HTTPS-SSL-14862570e7c480d4b619e40068f95761?pvs=4)
> [#164] https 적용

- BE/package-lock.json
- FE/src/components/Shell.tsx
closes #173
- 유저가 엄청 긴 한줄 쿼리를 날리면 자동으로 줄바꿈을 해줍니다.
자동 줄바꿈시는 들여쓰기가 자동으로 먹히던데 이건 해결방법을 모르겠습니다..엔터치면 들여쓰기가 없어지긴합니다.
- font 크기를 실제 ide에서 기본값으로 많이쓰이는 14로 변경하였습니다
- 자동 줄바꿈 되게 조정
- placeholder 상태관리 삭제
- 쉘 창 약간의 쉐도우 추가
- 에디터 높이 조절,setInputvalue로직 분리
> [#173] 자동 줄 바꿈 구현 및 font size 조절

- BE/src/config/query-database/admin-db-manager.service.ts
- BE/src/config/swagger/shell-swagger.decorator.ts
- BE/src/shell/shell.controller.ts
- BE/src/table/table.service.ts
closes #186 
이전에 테이블 컬럼 타입은 varchar라고만 보여줬는데 varchar(255) 같이 숫자까지 보일 수 있도록 하였습니다.
테이블 컬럼정보를 가져올때 DATA_TYPE->COLUMN_TYPE로 수정하였습니다.
shell쪽 스웨거 적용안되있어서 반영하였습니다.
> [#186] table 컬럼 타입 숫자까지 보이도록

- BE/src/config/query-database/admin-query-db.moudle.ts
- BE/src/config/query-database/user-db-manager.service.ts
- BE/src/config/redis/redis.module.ts
- BE/src/guard/guard.module.ts
- BE/src/query/query.controller.ts
- BE/src/query/query.service.ts
- BE/src/record/record.controller.ts
- BE/src/record/record.module.ts
- BE/src/record/record.service.ts
- BE/src/shell/shell.module.ts
- BE/src/table/table.module.ts
- BE/src/usage/usage.controller.ts
- BE/src/usage/usage.module.ts
- BE/src/usage/usage.service.ts
closes #188 
부하테스트 진행과 결과는 아래 노션으로 링크 달았습니다.
서비스에 핵심 부분이여서 모두가 한번씩은 봐주시고 피드백 주시면 감사하겠습니다.
userDB req주입으로 변경하면서 module수정하였습니다.
기능적으로 추가된건 없습니다.
scope를 제외함에 따라 전반적인 module 수정
[부하테스트 진행상황](https://spiffy-centipede-875.notion.site/connection-08fa943ec16d4eef8999c8cb836c4e21?pvs=4)
> [#188] 부하테스트 진행 및 userDB req직접 주입으로 변경

- FE/src/components/Shell.tsx
- FE/src/constants/constants.ts
- FE/src/constants/exampleQuery.ts
새로고침했을 때 쉘 크기가 다시 작아지는 이슈 해결
<br>
쉘 크기를 저장해서 쉘 크기가 다시 작아지는 이슈를 해결했습니다.
**[기타 작업]**
- char(1) -> char(255)로 수정
- create 예시 쿼리 수정
- 쉘 크기 새로고침 이후에도 작아지지 않도록 수정
<br>
> [#198, #199] 새로고침하고 쉘 크기가 다시 작아지는 이슈 수정

- BE/src/config/logger/logger.service.ts
- BE/src/interceptors/logging.interceptor.ts
- docker-compose.yml
#152 
로그 파일이 실제로 생성되는 위치가 달라서 이 docker-compose 파일을 수정하였습니다.
- 로그 파일 마운트 경로 수정
- 로그 메시지 형식 수정 및 설정
- 로그 아이디를 추가하여 확인할 수 요청응답 매핑
> [#152] 로깅 폴더 위치 수정 및 보완

- BE/src/common/exception/custom-exception.ts
- BE/src/common/exception/exception.handler.ts
- BE/src/config/query-database/admin-query-db.moudle.ts
- BE/src/config/query-database/query-db.moudle.ts
- BE/src/config/redis/redis.module.ts
- BE/src/config/swagger/query-swagger.decorator.ts
- BE/src/config/swagger/record-swagger.decorator.ts
- BE/src/interceptors/user-db-connection.interceptor.ts
- BE/src/main.ts
- BE/src/query/query.controller.ts
- BE/src/query/query.service.ts
- BE/src/record/record.controller.ts
- BE/src/record/record.module.ts
- BE/src/shell/shell.controller.ts
- BE/src/table/table.controller.ts
- BE/src/table/table.module.ts
- BE/src/usage/usage.controller.ts
- BE/src/usage/usage.module.ts
- BE/src/usage/usage.service.ts
closes #202 
데이터 용량이 행 수를 초과하면 롤백을 시키고 422에러를 반환시킵니다.
커넥션이 max를 넘어가면 429에러를 반환시킵니다.
인터셉터에서 요청시 커넥션을 생성하고 트랜잭션을 걸어줍니다
응답시 `DataLimitExceedException`이 나면 rollback을 시키고 정상응답이 오면 commit을 합니다
인터셉터에서 커넥션 생성시 최대 커넥션이상이 되면 mysql2에서 에러를 반환합니다. 이를 catch하여 429에러를 반환합니다.
```ts
@Injectable()
export class UserDBConnectionInterceptor implements NestInterceptor {
constructor(private readonly configService: ConfigService) {}
async intercept(
context: ExecutionContext,
next: CallHandler,
): Promise<Observable<any>> {
const request = context.switchToHttp().getRequest();
const identify = request.sessionID;
try {
request.dbConnection = await createConnection({
host: this.configService.get<string>('QUERY_DB_HOST'),
user: identify.substring(0, 10),
password: identify,
port: …
```
> [#202] 데이터 용량 제한 및 커넥션 에러 반환

- BE/src/usage/usage.service.ts
- FE/src/components/RecordTool.tsx
> 랜덤 데이터 추가 시 사용량 새로고침

- BE/package-lock.json
- BE/package.json
- BE/src/config/logger/logger.service.ts
- BE/src/config/query-database/admin-db-manager.service.ts
- BE/src/config/redis/redis.service.ts
- BE/src/middleware/session.middleware.ts
- BE/test/session/redis.service.spec.ts
- Jenkinsfile
close #162 
- RedisService에 대한 테스트 코드 작성
- 미들웨어에서 발생하는 에러 처리
세션과 밀접한 관련이 있는 메서드에 대한 테스트코드를 우선으로 작성하였습니다.
```ts
try {
await this.redisService.setNewSession(req.sessionID);
next();
} catch (error) {
res.status(500).json({
status: false,
error: {
code: 500,
message: error.message,
},
});
this.loggerService.error({
message: error.message,
stack: error.stack,
});
}
```
기존에는 미들웨어에서 발생하는 에러를 exception filter에서는 잡을 수 없어서 직접 작성하였습니다
근데 너무 더러운 것 같아서 좋은 개선 방안이 있다면 의견 부탁드립니다...ㅎㅎ
Redis에는 존재하지 않는 세션 정보지만, 쿼리 데이터베이스로는 존재하는 세션 정보에 대한 예외 처리가 되어 있지 않아서 해당 처리를 해주었습니다.
중복된 데이터베이스 생성에 대한 에러는 에러 응답으로 처리하지로 않기는 했지만
우선 에러 응답으로 전달되는 모습을 확인해두었습니다.
> [#162] RedisService 테스트 코드 작성

- BE/package-lock.json
- BE/package.json
- package-lock.json
- package.json
- schemas/index.ts
- schemas/query.ts
- schemas/record.ts
- schemas/shells.ts
body 가 필요한 api 요청에서 body 를 검증할 수 있도록 zod 스키마를 정의합니다.
`QueryDtoSchema` : 쿼리 실행 요청 api
`RecordColumnInfoSchema` : 랜덤 데이터 추가 요청 api
`UpdateShellDtoSchema` : 쉘 쿼리 수정 요청 api
> [#222] Request Validation 에 활용할 zod 스키마 정의

- FE/src/components/common/ResultTable.tsx
- FE/src/components/common/shell/Shell.tsx
쉘 실행시 실행버튼 위에 로딩 애니메이션을 추가했습니다.
<br>
> [#15] 쉘 실행시 로딩중임을 유저에게 보여준다.

- FE/package-lock.json
- FE/package.json
- FE/src/components/RecordTool.tsx
- FE/src/components/TableTool.tsx
- FE/src/components/common/shell/Shell.tsx
- FE/src/constants/constants.ts
- FE/src/types/interfaces.ts
- FE/src/util.ts
- FE/tsconfig.json
- FE/vite.config.ts
- schemas/index.ts
zod 스키마를 연동해서 입력을 검증하는 로직추가
- react hook form, zod으로 기존 폼 변경
- 검증후, 에러시 제출을 막고 에러 띄움
<br>
> [#189] 요청을 보내기 전, 사용자 입력을 검증한다

- BE/Dockerfile.test
- FE/Dockerfile
- FE/Dockerfile.test
- Jenkinsfile
- docker-compose.yml
- schemas/index.ts
zod 를 도입하여 모노레포 구조를 새로 구성하였습니다.
프로젝트 구성 폴더 구조 변경에 따라서 도커파일도 수정해주었습니다.
> [#237] zod 적용으로 인한 프로젝트 구조 변경에 따라 도커파일 수정
